---
title: "R Notebook"
output: html_notebook
---
#Librerias
```{r}
library(dplyr)
library(ggplot2)
library(MASS)
library(caret)
```
#Leemos el dataset
```{r}
data<-read.csv("dataset.csv")
glimpse(data)
```

#Analizamos las variables
#cantidad de datos 
```{r}
nrow(data)
```

#Satisfaccion
```{r}
summary(data$satisfaction_v2)
```

```{r}
barplot(table(data$satisfaction_v2),
        main= "Pasajeros",
        xlab= "Satisfechos",
        ylab= "Cantidad",
        col = rainbow(2))
```

#Sexo
```{r}
table(data$Gender)
```

```{r}
barplot(table(data$Gender),
        main= "Pasajeros",
        xlab= "Genero",
        ylab= "Cantidad",
        col = rainbow(2),
        ylim = c(0,70000))
```

#Edades

```{r}
summary(data$Age)
```

```{r}
plot(density(data$Age),
     type="l",
     col="blue",
     lwd= 2)
```
#Tendencia central
```{r}
paste("Media:", mean(data$Age))
paste("Mediana:", median(data$Age))
```


#Dataset
```{r}
summary(data)
```

#Arreglamos datos
```{r}
#Arreglamos la columna satisfecho 
data <- data %>%
  mutate(satisfaction_v2 = ifelse(satisfaction_v2 == 'satisfied', 1,0))
data$satisfaction_v2 <- factor(data$satisfaction_v2)
#Arreglamos la columna genero
data <- data %>%
  mutate(Gender = ifelse(Gender == 'Male', 1,0))
data$Gender <- factor(data$Gender)
```


#Verificamos data
```{r}
glimpse(data)
```


#Partimos la data
```{r}
set.seed(500)
tempdata <- createDataPartition(data$satisfaction_v2,
                                p = 0.6,
                                list = F,
                                times = 1)
trData <- data[tempdata,]
tsData <- data[-tempdata, ]
```

#Nombre de columnas
```{r}
colnames(trData)
```

```{r}
modelo.one <- trData %>%
  glm(formula = satisfaction_v2 ~ Gender + Age + Flight.Distance,
      family = "binomial")
summary(modelo.one)

```

#Preparamos La prediccion

```{r}
resultado <- tsData[,c("satisfaction_v2", "Gender", "Age", "Flight.Distance")]
prediccion <- predict(object = modelo.one,
                      newdata = resultado,
                      type = "response")
predicciones <- ifelse(prediccion >= 0.5,1,0)
resultado <- resultado %>%
  mutate(prob=prediccion) %>%
  mutate(Prediccion = predicciones)
resultado
```

#Es buen modelo o no 
```{r}
confusionMatrix(
  factor(resultado$Prediccion),
  factor(resultado$satisfaction_v2),
  positive = "1"
)
```

#Revisando variables




